services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: radpair-flask
    ports:
    - "5000:5000"
  client:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: radpair-react 
    ports:
      - "3000:3000"
