services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: react-flask-app-api
    ports:
    - "5000:5000"
  client:
    build:
      context: .
      dockerfile: dockerfile
    image: react-example-image 
    ports:
      - "3000:3000"
